name: 'TimeSynchronizer'
version: '${version}'
main: 'me.kvdpxne.ts.TimeSynchronizerPlugin'
authors: ['kvdpxne', 'mcdtm team']
description: '${description}'
website: 'https://github.com/mcdtm/time-synchronizer/'
